AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for Project

Parameters:
  ProjectName:
    Type: String
    Default: inventory
    Description: The name of the project.
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3a.micro
    Description: EC2 instance type.
  DBUsername:
    Type: String
    NoEcho: true
    Description: The database admin account username.
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    Type: String
    NoEcho: true
    Description: The database admin account password.
  S3AppUri:
    Type: String
    Description: App S3 uri
    Default: s3://buildia-inventory-bucket-service/inventory-service-0.0.1.jar

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref "InstanceType"
      ImageId: "ami-0427090fd1714168b" # ami amazon linux 2023
      IamInstanceProfile: !Ref "InstanceProfile"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Fn::ImportValue: "db-stack-SecGr1"
          SubnetId:
            Fn::ImportValue: 'db-stack-PublicSubnetAId'
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y java-21-amazon-corretto-devel
          sudo dnf install postgresql15 -y
          aws s3 cp ${S3AppUri} .
          
          DB_URL="jdbc:postgresql://$(aws cloudformation list-exports --query "Exports[?Name=='db-stack-RDSInstanceEndpoint'].Value" --output text):5432/$(aws cloudformation list-exports --query "Exports[?Name=='db-stack-DBName'].Value" --output text)"
          DB_USERNAME=${DB_USERNAME}
          DB_PASSWORD=${DB_PASSWORD}
          
          echo "export DB_URL=$DB_URL" | sudo tee -a /etc/profile
          echo "export DB_USERNAME=$DB_USERNAME" | sudo tee -a /etc/profile
          echo "export DB_PASSWORD=$DB_PASSWORD" | sudo tee -a /etc/profile
          source /etc/profile
          
          nohup java -jar inventory-service-0.0.1.jar  > /home/ec2-user/app.log 2>&1 &

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles: [!Ref "EC2InstanceRole"]

  EC2InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EC2S3Access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: "arn:aws:s3:::*"
        - PolicyName: "EC2CFListExports"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cloudformation:Describe*"
                  - "cloudformation:List*"
                  - "cloudformation:Get*"
                Resource: "*"

Outputs:
  InstanceId:
    Description: "InstanceId of the newly created EC2 instance"
    Value: !Ref "EC2Instance"
  PublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt "EC2Instance.PublicIp"